name: Build and Push Docker Image

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/react-hello

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Clone Flux Repo and Update Image Tag
        run: |
          git clone https://x-access-token:${{ secrets.FLUX_REPO_TOKEN }}@github.com/Lachitha/flux-react-deploy.git
          cd flux-react-deploy/apps/react
          echo "Updating deployment image to ${{ env.IMAGE_NAME }}:${{ github.sha }}"
          
          # Install yq v4
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
          sudo chmod +x /usr/bin/yq

          # Update image tag in deployment.yaml
          yq -i '.spec.template.spec.containers[0].image = "${{ env.IMAGE_NAME }}:${{ github.sha }}"' react-deployment.yaml

          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update image to ${{ env.IMAGE_NAME }}:${{ github.sha }}"
          git push origin main
